var settings = {
    "options": { "backgroundType": "image", "backgroundOverlayOpacity": 0.8, "backgroundBlur": 0, "backgroundScale": 1, "displayBranding": "yes", "logoOpacity": 0.3, "logoScale": "1.8", "frameWidth": "4", "sceneTitle": "Hurtrus", "tagline": "The stream is about to begin!" },
    "colors": { "backgroundOverlay": "rgba(54, 53, 58, 1)", "accentColor": "rgba(234, 220, 4, 1)", "frameColor": "rgba(20, 187, 189, 1)", "primaryTextColor": "rgba(255, 255, 255, 1)", "subTextColor": "rgba(234, 220, 4, 1)", "contentBackgrounds": "rgba(255, 255, 255, .1)" },
    "labels": { "displayLabels": "yes", "labelOneHeading": "New Follower", "labelOnePath": "most_recent_follower", "labelTwoHeading": "Latest Tip", "labelTwoPath": "most_recent_donator", "labelThreeHeading": "Biggest Tip", "labelThreePath": "monthly_top_donator", "labelFourHeading": "Recent Sub", "labelFourPath": "most_recent_subscriber" },
    "schedule": { "displaySchedule": "yes", "sunday": "9:30 - Midnight EST", "monday": "9:30 - Midnight EST", "tuesday": "9:30 - Midnight EST", "wednesday": "9:30 - Midnight EST", "thursday": "9:30 - Midnight EST", "friday": "9:30 - Midnight EST", "saturday": "9:30 - Midnight EST" },
    "scaling": { "socialMediaScale": 1, "labelsScale": 1, "scheduleScale": 1, "countdownScale": 1 },
    "fonts": { "primaryFont": "", "subFont": "", "titleSize": "200", "titleVerticalOffset": "-103", "subtitleSize": "74", "subtitleVerticalOffset": 0, "labelNameSize": 20, "labelNameVerticalOffset": 0, "labelHeaderSize": 12, "labelHeaderVerticalOffset": 0, "countdownTimeSize": 60, "countdownTimeVerticalOffset": 0, "countdownMessageSize": 24, "countdownMessageVerticalOffset": 0, "countdownEndMessageSize": 60, "countdownEndMessageVerticalOffset": 0 },
    "countdown": { "displayCountdown": "yes", "countdownTime": "5", "countdownMessage": "until the stream starts!", "countdownOverMessage": "Let's go!" },
    "social": { "displaySocial": "yes", "twitch": "Hurtrus", "twitterHeader": "Follow Me On Twitter", "twitter": "@Hurtrus_Streaming", "facebookHeader": "", "facebook": "", "instagramHeader": "", "instagram": "", "youtubeHeader": "Subscribe On YouTube", "youtube": "HurtrusStreaming" }
};